# Generated by Django 6.0.1 on 2026-01-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_today', models.IntegerField(default=0)),
                ('borrow_month', models.IntegerField(default=0)),
                ('overdue_count', models.IntegerField(default=0)),
                ('active_members', models.IntegerField(default=0)),
                ('borrow_today_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('borrow_month_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_members_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dashboard_stats',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OverdueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=255)),
                ('member_name', models.CharField(max_length=255)),
                ('due_date', models.DateField()),
                ('days_overdue', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'overdue_books',
            },
        ),
        migrations.CreateModel(
            name='TopReader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('book_count', models.IntegerField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'top_readers',
                'ordering': ['rank'],
            },
        ),
    ]
