# Generated by Django 6.0.1 on 2026-02-01 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_account_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='club_permission',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Được phép thêm CLB'), ('rejected', 'Từ chối')], default='pending', max_length=20),
        ),
    ]
