# Generated by Django 6.0.1 on 2026-02-01 05:15

from django.db import migrations, models


def convert_old_permissions(apps, schema_editor):
    Account = apps.get_model("api", "Account")
    mapping = {"pending": "user", "approved": "department_member", "rejected": "user"}
    for acc in Account.objects.all():
        old = acc.club_permission or "pending"
        acc.club_permission = mapping.get(old, "user")
        acc.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_add_account_club_permission'),
    ]

    operations = [
        migrations.RunPython(convert_old_permissions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='account',
            name='club_permission',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('department_head', 'Trưởng ban'), ('department_member', 'Thành viên các ban'), ('user', 'Người dùng')], default='user', max_length=30),
        ),
    ]
