# Generated by Django 6.0.1 on 2026-02-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_change_account_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='display_email',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
