# Generated by Django 6.0.1 on 2026-02-01 06:00

from django.db import migrations, models


def migrate_department_head(apps, schema_editor):
    Account = apps.get_model("api", "Account")
    Account.objects.filter(club_permission="department_head").update(club_permission="head_book")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_display_email'),
    ]

    operations = [
        migrations.RunPython(migrate_department_head, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='account',
            name='club_permission',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('head_book', 'Trưởng ban Quản Lý Sách'), ('head_communication', 'Trưởng ban Truyền thông - Đối Ngoại'), ('head_hr_finance', 'Trưởng ban Nhân sự - Tài Chính'), ('department_member', 'Thành viên các ban'), ('user', 'Người dùng')], default='user', max_length=35),
        ),
    ]
