# Generated by Django 6.0.1 on 2026-02-01 06:02

from django.db import migrations, models


def migrate_department_member(apps, schema_editor):
    Account = apps.get_model("api", "Account")
    Account.objects.filter(club_permission="department_member").update(club_permission="member_book")


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_expand_role_choices'),
    ]

    operations = [
        migrations.RunPython(migrate_department_member, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='account',
            name='club_permission',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('head_book', 'Trưởng ban Quản Lý Sách'), ('head_communication', 'Trưởng ban Truyền thông - Đối Ngoại'), ('head_hr_finance', 'Trưởng ban Nhân sự - Tài Chính'), ('member_book', 'Thành viên ban Quản lý sách'), ('member_communication', 'Thành viên ban Truyền thông - Đối Ngoại'), ('member_hr_finance', 'Thành viên ban Nhân sự - Tài Chính'), ('user', 'Người dùng')], default='user', max_length=35),
        ),
    ]
