# Generated by Django 6.0.1 on 2026-02-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_notification_sender_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='club_permission',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('chairperson', 'Chủ nhiệm'), ('vice_chairperson', 'Phó chủ nhiệm'), ('head_book', 'Trưởng ban Quản Lý Sách'), ('vice_head_book', 'Phó ban Quản Lý Sách'), ('head_communication', 'Trưởng ban Truyền thông - Đối Ngoại'), ('vice_head_communication', 'Phó ban Truyền thông - Đối Ngoại'), ('head_hr_finance', 'Trưởng ban Nhân sự - Tài Chính'), ('vice_head_hr_finance', 'Phó ban Nhân sự - Tài Chính'), ('member_book', 'Thành viên ban Quản lý sách'), ('member_communication', 'Thành viên ban Truyền thông - Đối Ngoại'), ('member_hr_finance', 'Thành viên ban Nhân sự - Tài Chính'), ('user', 'Người dùng')], default='user', max_length=35),
        ),
        migrations.CreateModel(
            name='NotificationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_reads', to='api.account')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='api.notification')),
            ],
            options={
                'db_table': 'notification_reads',
                'ordering': ['-read_at'],
                'constraints': [models.UniqueConstraint(fields=('notification', 'account'), name='unique_notif_read')],
            },
        ),
    ]
