# Generated by Django 6.0.1 on 2026-02-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_add_email_verification_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingGiftConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', models.TextField(blank=True)),
                ('items', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ranking_gift_config',
                'ordering': ['-id'],
            },
        ),
    ]
