# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_ranking_gift_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='return_notes',
            field=models.TextField(blank=True, help_text='Ghi chú tình trạng sách khi trả (hư hỏng, v.v.)'),
        ),
    ]
