# Generated by Django 6.0.1 on 2026-02-24 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_borrow_record_return_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, help_text='Tài khoản ghi nhận phiếu mượn (người ghi mượn sách).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='borrow_records_recorded', to='api.account'),
        ),
    ]
