# Generated by Django 6.0.1

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_borrow_record_recorded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='guest_class',
            field=models.CharField(blank=True, help_text='Lớp (ghi chú) khi mượn không tài khoản.', max_length=255),
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Tên người mượn khi không có tài khoản.', max_length=255),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='member',
            field=models.ForeignKey(
                blank=True,
                help_text='Thành viên có tài khoản; null nếu người mượn là khách (không tài khoản).',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='api.member',
            ),
        ),
    ]
