# Generated by Django 6.0.1 on 2026-02-27 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_add_book_purchase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='student_id_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
